import streamlit as st
st.write("<h1 style='text-align: center;'>Description of Imaging Orders</h1>", unsafe_allow_html=True)
st.subheader("CT Head Without Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("CT Maxillofacial Without Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("CT Soft Tissue Neck With Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("MR Angio Brain Without Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("MRI Brain and Orbits WO/W Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("MRI Brain WO/W Contrast Head Without Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("MRI Complete Spin WO/W Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
st.subheader("MRI Pituitary WO/W Contrast")
st.write("Write a brief explanation about CT Head Without Contrast")
